name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'
        cache: 'pnpm'
    - name: Install pnpm
      run: |
        npm install -g pnpm
        echo "PATH=$(npm bin -g):$PATH" >> $GITHUB_ENV
    - name: Install dependencies
      run: pnpm install
    - name: Run build
      run: pnpm run build
    - name: Install Playwright browser
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: pnpm test
