name: CI

on:
  push:
    branches: [ main, topic/webextension ]
  pull_request:
    branches: [ main, topic/webextension ]

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository }}/devin-status-checker:latest

  ci:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/devin-status-checker:latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: pnpm install --frozen-lockfile

    - name: Type check
      run: pnpm run type-check

    - name: Run build
      run: pnpm run build

    - name: Install Playwright browser
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: pnpm test
